const WORKER_ACTION = {
  PERFORM_QUERY: 'PERFORM_QUERY',
  EXIT_PROCESS: 'EXIT_PROCESS',
};

const WORKER_STATUS = {
  READY: 'READY',
  FINISHED: 'FINISHED',
};

module.exports = {
  WORKER_ACTION,
  WORKER_STATUS,
};
